name: RSS Feed Generator

on:
  schedule:
    # 每天 UTC 时间 0点、12点 各执行一次（北京时间 8点、20点）
    - cron: "0 0,12 * * *"
  workflow_dispatch:  # 允许手动触发

jobs:
  generate-feeds:
    runs-on: ubuntu-latest

    steps:
      # 步骤1：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤2：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 步骤3：安装依赖（包括 Playwright 浏览器）
      - name: Install dependencies
        run: |
          # 更新软件源列表
          sudo apt-get update

          # 安装基础编译工具
          sudo apt-get install -y build-essential

          # 安装修正后的依赖包
          sudo apt-get install -y \
          libasound2t64 \          # 替代旧版 libasound2
          libffi-dev \             # 替代 libffi7
          libx264-dev \            # 替代 libx264-163
          libnss3 \
          libnspr4 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdrm2 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxrandr2 \
          libgbm1 \
          libgtk-3-0 \
          libpango-1.0-0 

          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
          playwright install-deps chromium  # 明确指定 Chromium 依赖

      # 步骤4：运行爬虫生成 RSS
      - name: Generate RSS feeds
        run: python main.py  # 确保你的代码文件名正确

      # 步骤5：提交生成的 XML 文件（可选）
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add *.xml
          git commit -m "Auto-update RSS feeds" || echo "No changes to commit"
          git push